//
//  StationRegistry.swift
//  OpenFlowMobile
//
//  Loads data/station_registry.json (bundled into the app at build time).
//  The registry is generated by scripts/build_registry.py and refreshed via
//  .github/workflows/registry-update.yml whenever upstream supported sites
//  or the closest GHCND stations change.
//

import Foundation

struct StationRegistry: Decodable {
    let schemaVersion: Int
    let generatedUtc: String
    let encoderWindowEndOffsetDays: Int
    let sites: [String: SiteMetadata]

    func site(for id: String) -> SiteMetadata? { sites[id] }

    static func loadBundled() throws -> StationRegistry {
        guard let url = Bundle.main.url(forResource: "station_registry", withExtension: "json") else {
            throw RegistryError.missing
        }
        let data = try Data(contentsOf: url)
        let dec = JSONDecoder()
        dec.keyDecodingStrategy = .convertFromSnakeCase
        return try dec.decode(StationRegistry.self, from: data)
    }
}

struct SiteMetadata: Decodable {
    let agency: String
    let siteId: String
    let name: String?
    let lat: Double?
    let lon: Double?
    let huc8: String?
    let snotelTriplets: [String]
    let ghcndId: String?
    let ghcndDistanceKm: Double?
    let notes: [String]
}

enum RegistryError: LocalizedError {
    case missing
    case siteUnknown(String)
    case missingField(site: String, field: String)

    var errorDescription: String? {
        switch self {
        case .missing:
            return "station_registry.json not bundled with the app"
        case .siteUnknown(let id):
            return "Site \(id) is not in the station registry"
        case .missingField(let site, let field):
            return "Registry entry for \(site) is missing required field \(field)"
        }
    }
}
